apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          # we can remove the env
          env:
            - name: MYSQL_ROOT_PASSWORD
             # value: "root@123"
              value: "password"
            - name: MYSQL_DATABASE
              value: "contacts"
#              valueFrom:
#                secretKeyRef:
#                  name: mysql-secret
#                  key: mysql-root-password
          ports:
            - containerPort: 3306
          volumeMounts:           
             # mountPath: /var/lib/mysql
            - name: app-sqldata
            mountPath: /var/www/html/data
volumes:
  - name: app-sqldata
    persistentVolumeClaim:
      claimName: mysql-pvc
